### ISSUE TITLE
Exercise 2 - HTML

### ISSUE THREAD

**Issue by huongcucnguyen** [huongcucnguyen/Reactjs2021#2]
# Problem 課題
- Please create a html page with the following required content: 
- 要求された内容に沿って、htmlページを作成する
![Baitap2](https://user-images.githubusercontent.com/91561515/135383018-a7550db0-950c-4a2e-9be3-41a862aa89dc.jpg)

# Goals 目的
- Can use basic commands commonly used in HTML
- HTMLの一般的に利用されている基本的なコマンドの使用可能

# Solutions ソリューション
- Research and practice with https://www.w3schools.com/html/
- https://www.w3schools.com/html/でリサーチ及び実践

**Comment by william-monroy** [comment]
Hi @huongcucnguyen , I would like to work on this issue. What requirements do I have to meet when making the page?

**Comment by huongcucnguyen** [comment]
Done!
<img width="736" alt="Screen Shot 2021-09-30 at 15 46 34" src="https://user-images.githubusercontent.com/91561515/135419870-b0608a4d-551b-4eac-baf5-2bfffdaf3569.png">

**Comment by huongcucnguyen** [comment]
> Hi @huongcucnguyen , I would like to work on this issue. What requirements do I have to meet when making the page?

Hello @william-monroy 
Nice to meet you.
The requirement is that you create a web page with displayed content like the image I attached in this issue.
Have a good day!

**Comment by william-monroy** [comment]
Nice to meet you too, @huongcucnguyen Could you assign me this issue?

**Comment by huongcucnguyen** [comment]
> Nice to meet you too, @huongcucnguyen Could you assign me this issue?

@william-monroy 
Yes sure.
I think you will need the text content in Vietnamese. So I'll share it with you here:
```
Bài 02: Sử dụng các tag cơ bản (tt)
Yêu cầu
Thiết kế trang web có nội dung như sau
MẸ
Mẹ là cả một trời thương nhớ
Mẹ là cả một thiên đường trần gian
Công ơn cha mẹ tựa biển trời
Làm sao báo hiếu hỡi người ơi?
Nếu chưa báo hiếu đừng bất hiếu
Bất hiếu làm ta khổ muôn đời
Một đời vốn liếng mẹ trao
Mẹ cho tất cả mẹ nào giữ riêng
Mẹ hiền như một bà tiên
Mẹ theo con suốt hành trình con đi
```
Have a nice evening!
